---
abstract: 'Just another HTML table generating DBI extension.'
author:
  - 'Jeff Anderson <jeffa@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-HTML
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 0
  Spreadsheet::HTML: 1.02
  perl: 5.006
resources:
  bugtracker: https://github.com/jeffa/DBIx-HTML/issues
  homepage: https://github.com/jeffa/DBIx-HTML
  repository: https://github.com/jeffa/DBIx-HTML.git
version: 1.01
